name = "make-it-so-cli"

# ğŸ‘‡ Project-scoped settings available to all plugins
[project_variables]
# â€” User-created (optional) env variables accessible by plugins through the ctx object:
foo = "bar"            # â† EXAMPLE of a project-scoped variable
